// Code generated by encore. DO NOT EDIT.

package member

import "context"

// These functions are automatically generated and maintained by Encore
// to simplify calling them from other services, as they were implemented as methods.
// They are automatically updated by Encore whenever your API endpoints change.

// Interface defines the service's API surface area, primarily for mocking purposes.
//
// Raw endpoints are currently excluded from this interface, as Encore does not yet
// support service-to-service API calls to raw endpoints.
type Interface interface {
	// Returns all members sorted by name
	Members(ctx context.Context) (*ListResponse, error)

	// Returns the count of members
	MembersCount(ctx context.Context) (MembersCountStruct, error)

	// Returns a MemberStruct
	Member(ctx context.Context, name string) (*MemberStruct, error)
}
