# Staging

## Members

### GET members
http://127.0.0.1:4000/members

### GET Member
http://127.0.0.1:4000/member/1

### GET Members count
http://127.0.0.1:4000/members/count

## Products

### GET product trainings
http://127.0.0.1:4000/product/trainings

### GET product training
http://127.0.0.1:4000/product/training/Hybrid Cloud Strategie

## Locations

### GET locations
http://127.0.0.1:4000/about/locations

## Carriers

### GET careers
http://localhost:4000/careers