on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

name: Release Please

jobs:
  release:
    name: 📦 Release
    runs-on: ubuntu-latest
    outputs:
      upload-url: ${{ steps.release.outputs.upload_url }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          release-type: simple
          config-file: .release-please-config.json
          manifest-file: .release-please-manifest.json

      - name: Print the release URL if present
        if: ${{ steps.release.outputs.upload_url }}
        run: |
          echo "Upload URL: ${{ steps.release.outputs.upload_url }}"
